### ISSUE TITLE
Help - How can you import only the required components?

### ISSUE THREAD

**Issue by dashc** [Hokid/vue-loaders#1]
I wish to only import relevant loaders into my project, instead of load them all and only using one.

I was thinking this:
`import {'ball-beat-loader'} from 'vue-loaders';`
or 
`import {BallBeatLoader} from 'vue-loaders';`

But doesn't work. I'm new to VueJS/ES6 so couldn't figure this one out?

**Comment by Hokid** [comment]
I'm looking for a good solution for this case and I plan to add this feature soon

**Comment by Hokid** [comment]
@dashc you can update vue-loaders to 2.0.0 to get this feature. Additinaly, read updated documentaion, ther is some changes.
