### ISSUE TITLE
The package name made me confused

### ISSUE THREAD

**Issue by fy0** [Hokid/vue-loaders#3]
Yesterday I upgrade my project to vue cli 3 style. Because of package.json changed a lot,  I had to rewrite it.

I checked my old package.json items one by one and added them to the new file. 

When I meet vue-loaders, I thought it's a package like xxx-loader or a old package from vue team, so I removed it from my project.

Finally I realized mistake when I found my loading animates were gone.

**Comment by Hokid** [comment]
@fy0, sorry about that. Currently i can`t change the package name, but i gonna think about that.

**Comment by fy0** [comment]
@Hokid Got it, and thanks for your works.
