### ISSUE TITLE
Allow for class-based coloring

### ISSUE THREAD

**Issue by TheStoof** [Hokid/vue-loaders#4]
Currently, the **color** defaults to #ffffff. Unless the class has !important on the color, #ffffff will be used. This makes it difficult to be used with Bootstrap themes that would otherwise change the color of the loader properly.

**Comment by Hokid** [comment]
You can set `color` component property to `currentColor`. Like this:

```html
<vue-loaders-cube-transition class="class-based-color" color="currentColor"></vue-loaders-cube-transition>
```

```css
.class-based-color {
  color: red;
}
```

See more examples: https://codepen.io/Hokid/pen/xoaZew
