### ISSUE TITLE
Css class .ball-spin-fade-loader not available in production build

### ISSUE THREAD

**Issue by radud** [Hokid/vue-loaders#9]
Hi there, 

Thank you for this awesome library. I have an issue when I compile the app for production.
.ball-spin-fade-loader class are not present.

Do you know about this?

Many thanks,
Radu

**Comment by Hokid** [comment]
Hi, Radu! Thank you! 

Do you import `vue-loaders/dist/vue-loaders.css` in your project?

**Comment by radud** [comment]
Hi Hokid, 

Thank you for the very prompt answer. 

This is how I use: 

```
import 'vue-loaders/dist/vue-loaders.css';
import VueLoaders from 'vue-loaders';
import VueLoadersBallBeat from 'vue-loaders/dist/loaders/ball-beat';

Vue.use(VueLoaders);
```

Then in template I use both forms: 

`
<vue-loaders name="ball-spin-fade-loader" :color="color" :scale="scale"></vue-loaders> <span v-if="text">{{ text }}</span>
<vue-loaders-ball-spin-fade-loader :color="color" :scale="scale"/> 
`

When I use 

vue-cli-service serve -> works ok 
vue-cli-service build -> css classes are missing. I use vue cli 3. I haven't configured anything regarding css loading. I assume this is something that cli does automatically?

Many thanks, 
Radu D

**Comment by Hokid** [comment]
> Hi Hokid,
> 
> Thank you for the very prompt answer.
> 
> This is how I use:
> 
> ```
> import 'vue-loaders/dist/vue-loaders.css';
> import VueLoaders from 'vue-loaders';
> import VueLoadersBallBeat from 'vue-loaders/dist/loaders/ball-beat';
> 
> Vue.use(VueLoaders);
> ```
> 
> Then in template I use both forms:
> 
> `<vue-loaders name="ball-spin-fade-loader" :color="color" :scale="scale"></vue-loaders> <span v-if="text">{{ text }}</span> <vue-loaders-ball-spin-fade-loader :color="color" :scale="scale"/> `
> 
> When I use
> 
> vue-cli-service serve -> works ok
> vue-cli-service build -> css classes are missing. I use vue cli 3. I haven't configured anything regarding css loading. I assume this is something that cli does automatically?
> 
> Many thanks,
> Radu D

Can you please create repo with minimal code example to reproduce the bug? I will clone that repo and make production build to investigate the problem.

**Comment by Hokid** [comment]
@radud what exactly versions of vue-loaders and vue cli you use? I try use vue-loaders 4.1.1 and vue cli 3.12.1 and can`t confirm tthe problem .

**Comment by Hokid** [comment]
> I haven't configured anything regarding css loading. I assume this is something that cli does automatically?
Yes

**Comment by Hokid** [comment]
@radud if you still have the problem then reopen issue and provide steps to reproduce or repository with example.
